import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {tables, slotsFor, availableSlots, isValidReservation, tableAvailable, shiftDay} from '../dist/booking.js';
import {openingState} from '../dist/hours.js';
const config=JSON.parse(await readFile(new URL('../dist/config.json',import.meta.url)));
const now=new Date('2026-10-02T14:00:00Z');
assert.equal(slotsFor(config,'2026-10-01',now).length,0,'No dates in the past');
assert.equal(slotsFor(config,'2026-10-05',now).length,0,'Monday is closed');
assert.equal(slotsFor(config,shiftDay('2026-10-02',91),now).length,0,'90-day window');
const friday=slotsFor(config,'2026-10-02',now);
assert.equal(friday[0].label,'18:00');
assert.equal(friday.at(-1).label,'23:30','90 minutes must fit before 01:00 closing');
assert.equal(slotsFor(config,'2026-10-02',new Date('2026-10-02T16:15:00Z'))[0].label,'19:00','30-minute lead time in Rome');
const table=tables.find(t=>tableAvailable(t,'2026-10-03',1080,2,[]));
const booking={id:'test',table:table.id,date:'2026-10-03',minute:1080,party:2,seats:[1,2]};
assert.ok(isValidReservation(booking,config,[],now));
assert.ok(!isValidReservation({...booking,seats:[1,1]},config,[],now),'No duplicate seats');
assert.ok(!isValidReservation({...booking,party:9},config,[],now),'Capacity is enforced');
assert.ok(!isValidReservation({...booking,minute:1110},config,[booking],now),'Overlapping reservations are rejected');
assert.ok(isValidReservation({...booking,minute:1170},config,[booking],now),'Adjacent 90-minute sessions are allowed');
assert.equal(availableSlots({...config,exceptions:{'2026-10-03':[]}},'2026-10-03',2,[],now).length,0,'Exceptional closures');
assert.ok(openingState(config,new Date('2026-10-02T22:30:00Z')).open,'Friday service remains open after midnight');
assert.ok(!openingState(config,new Date('2026-10-02T23:01:00Z')).open,'Friday service closes at 01:00 Rome');
console.log('14 booking and opening-hours assertions passed');
